# ========================== APPLICATION ==========================
spring.application.name=uteexpress

# ========================== DATASOURCE (PostgreSQL) ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/ute_express
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================== JPA / HIBERNATE ==========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================== JSON SERIALIZATION ==========================
# Tránh lỗi LazyInitialization khi serialize entity có @ManyToOne LAZY
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null
